name: simple_pet_app
description: A simple Flutter application to demonstrate the Cubit pattern for state management. The app shows a text with an icon, and when the text is clicked, it changes both the text and the icon.
version: 1.0.0
environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^7.3.0
  bloc: ^7.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^8.0.0
  mocktail: ^0.3.0

flutter:
  uses-material-design: true